### ISSUE TITLE
"style" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by samidevio** [SvenWesterlaken/vue-wavify#1]
I got the warning: [Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

My code
`<vue-wavify  :height="30" fill="#5e72e4"></vue-wavify>`

How to solve this problem?

Thanks. :)

**Comment by SvenWesterlaken** [comment]
Will look into this later this week. Will report back afterwards @samidevio :)
